# Pages CMS Configuration for ParableForge
# Documentation: https://pagescms.org/docs

content:
  - name: adventures
    label: Adventures
    path: src/content/docs/grimoire/adventures
    extension: mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
        description: The adventure title shown in the header

      - name: description
        label: Description
        type: text
        required: true
        description: A brief description of the adventure

      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - name: label
            label: Sidebar Label
            type: string
            required: true
            description: Short name for sidebar navigation
          - name: order
            label: Sort Order
            type: number
            description: Lower numbers appear first

      - name: body
        label: Adventure Content
        type: rich-text
        description: The full adventure script and content

media:
  input: public/images
  output: /images

settings:
  branch: main
  name: ParableForge
